### ISSUE TITLE
[Support Request] 在一次runtime error崩溃后，无法再成功启动

### ISSUE THREAD

**Issue by kyleli666** [daeuniverse/dae#354]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

daed使用中，突然发生了一次runtime error，看起来时dae哪里出错了
```
11月 10 19:06:18 proxy-sh daed[708373]: time="Nov 10 19:06:18" level=info msg="192.168.100.111:63489 <-> 202.96.209.5:53" _qname=clientservices.googleapis.com. dialer=direct dscp=0 mac="00:15:5d:01:79:4b" network="udp4(DNS)" outboun>
11月 10 19:06:18 proxy-sh daed[708373]: time="Nov 10 19:06:18" level=info msg="192.168.100.136:54585 <-> clientservices.googleapis.com:443" dialer="HK PROXY-HK" dscp=0 ip="180.163.150.162:443" mac="f0:2f:74:dc:c9:6e" network=tcp4 ou>
11月 10 19:06:18 proxy-sh daed[708373]: time="Nov 10 19:06:18" level=info msg="192.168.100.136:54586 <-> accounts.google.com:443" dialer="HK PROXY-HK" dscp=0 ip="142.250.199.77:443" mac="f0:2f:74:dc:c9:6e" network=tcp4 outbound=prox>
11月 10 19:06:18 proxy-sh daed[708373]: time="Nov 10 19:06:18" level=info msg="192.168.100.111:62927 <-> 8.8.8.8:53" _qname=www.googleapis.com. dialer=direct dscp=0 mac="00:15:5d:01:79:4b" network="udp4(DNS)" outbound=direct pid=0 p>
11月 10 19:06:18 proxy-sh daed[708373]: time="Nov 10 19:06:18" level=info msg="192.168.100.111:62043 <-> 8.8.8.8:53" _qname=accounts.google.com. dialer=direct dscp=0 mac="00:15:5d:01:79:4b" network="udp4(DNS)" outbound=direct pid=0 >
11月 10 19:06:18 proxy-sh daed[708373]: time="Nov 10 19:06:18" level=info msg="192.168.100.111:62930 <-> 8.8.8.8:53" _qname=www.googleapis.com. dialer=direct dscp=0 mac="00:15:5d:01:79:4b" network="udp4(DNS)" outbound=direct pid=0 p>
11月 10 19:06:18 proxy-sh daed[708373]: panic: runtime error: slice bounds out of range [1489:1215]
11月 10 19:06:18 proxy-sh daed[708373]: goroutine 1827846 [running]:
11月 10 19:06:18 proxy-sh daed[708373]: github.com/daeuniverse/dae/component/sniffing/internal/quicutils.ReassembleCryptoToBytesFromPool({0xc0027e7000, 0x4bf, 0x800})
11月 10 19:06:18 proxy-sh daed[708373]:         github.com/daeuniverse/dae@v0.2.0/component/sniffing/internal/quicutils/relocation.go:88 +0x205
11月 10 19:06:18 proxy-sh daed[708373]: github.com/daeuniverse/dae/component/sniffing.extractSniFromQuicPayload({0xc0027e7000?, 0x16?, 0x800?})
11月 10 19:06:18 proxy-sh daed[708373]:         github.com/daeuniverse/dae@v0.2.0/component/sniffing/quic.go:180 +0x247
11月 10 19:06:18 proxy-sh daed[708373]: github.com/daeuniverse/dae/component/sniffing.sniffQuicBlock({0xc00092f800, 0x4e2, 0x11eed80?})
11月 10 19:06:18 proxy-sh daed[708373]:         github.com/daeuniverse/dae@v0.2.0/component/sniffing/quic.go:149 +0x953
11月 10 19:06:18 proxy-sh daed[708373]: github.com/daeuniverse/dae/component/sniffing.(*Sniffer).SniffQuic(0x56120f?)
11月 10 19:06:18 proxy-sh daed[708373]:         github.com/daeuniverse/dae@v0.2.0/component/sniffing/quic.go:47 +0x4c
11月 10 19:06:18 proxy-sh daed[708373]: github.com/daeuniverse/dae/component/sniffing.sniffGroup({0xc002f81840, 0x1, 0x135d980?})
11月 10 19:06:18 proxy-sh daed[708373]:         github.com/daeuniverse/dae@v0.2.0/component/sniffing/sniffer.go:53 +0x4b
11月 10 19:06:18 proxy-sh daed[708373]: github.com/daeuniverse/dae/component/sniffing.(*Sniffer).SniffUdp(0xc003fcede0)
11月 10 19:06:18 proxy-sh daed[708373]:         github.com/daeuniverse/dae@v0.2.0/component/sniffing/sniffer.go:112 +0x13d
11月 10 19:06:18 proxy-sh daed[708373]: github.com/daeuniverse/dae/control.(*ControlPlane).handlePkt(0xc001ad5950, 0xc00000e028, {0xc00092f800, 0x4e2, 0x800}, {{{0xc0028ac7e0?, 0xc00267c000?}, 0xc0000a4cf0?}, 0xe2a0?}, {{{0x0, ...},>
11月 10 19:06:18 proxy-sh daed[708373]:         github.com/daeuniverse/dae@v0.2.0/control/udp.go:145 +0x385
11月 10 19:06:18 proxy-sh daed[708373]: github.com/daeuniverse/dae/control.(*ControlPlane).Serve.func5.1({0xc00092f800, 0x4e2, 0x800}, {0xc003fe7040?, 0xc002b20520?, 0xc00153f320?}, {{{0x0, 0xffffc0a86488}, 0xc0000a4d08}, 0xd6ac})
11月 10 19:06:18 proxy-sh daed[708373]:         github.com/daeuniverse/dae@v0.2.0/control/control_plane.go:778 +0x571
11月 10 19:06:18 proxy-sh daed[708373]: created by github.com/daeuniverse/dae/control.(*ControlPlane).Serve.func5
11月 10 19:06:18 proxy-sh daed[708373]:         github.com/daeuniverse/dae@v0.2.0/control/control_plane.go:737 +0xef
11月 10 19:06:18 proxy-sh systemd[1]: daed.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

### Current Behavior

然后尝试重启daed服务，但无法成功启动。daed的管理界面也无法访问。
```
11月 11 12:23:19 v2rayA daed[1240]: time="2023-11-11T12:23:19+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.102:53 (dialer: direct): read udp [::]:47744: i/o timeout"
11月 11 12:23:19 v2rayA daed[1240]: time="2023-11-11T12:23:19+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.102:53 (dialer: direct): read udp [::]:48035: i/o timeout"
11月 11 12:23:19 v2rayA daed[1240]: time="2023-11-11T12:23:19+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.102:53 (dialer: direct): read udp [::]:35637: i/o timeout"
11月 11 12:23:19 v2rayA daed[1240]: time="2023-11-11T12:23:19+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.102:53 (dialer: direct): read udp [::]:57065: i/o timeout"
11月 11 12:23:19 v2rayA daed[1240]: time="2023-11-11T12:23:19+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:51642: i/o timeout"
11月 11 12:23:19 v2rayA daed[1240]: time="2023-11-11T12:23:19+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.102:53 (dialer: direct): read udp [::]:48963: i/o timeout"
11月 11 12:23:19 v2rayA systemd[1]: Stopping daed.service - daed is a integration solution of dae, API and UI....
11月 11 12:23:19 v2rayA systemd[1]: daed.service: Deactivated successfully.
11月 11 12:23:19 v2rayA systemd[1]: Stopped daed.service - daed is a integration solution of dae, API and UI..
11月 11 12:23:19 v2rayA systemd[1]: daed.service: Consumed 10.187s CPU time.
11月 11 12:29:33 v2rayA systemd[1]: Started daed.service - daed is a integration solution of dae, API and UI..
11月 11 12:29:33 v2rayA daed[3948]: time="2023-11-11T12:29:33+08:00" level=info msg="Loading eBPF programs and maps into the kernel..."
11月 11 12:29:33 v2rayA daed[3948]: time="2023-11-11T12:29:33+08:00" level=info msg="The loading process takes about 120MB free memory, which will be released after loading. Insufficient memory will cause loading failure."
^[[B^[[A11月 11 12:29:41 v2rayA daed[3948]: time="2023-11-11T12:29:41+08:00" level=info msg="Loaded eBPF programs and maps"
11月 11 12:29:41 v2rayA daed[3948]: time="2023-11-11T12:29:41+08:00" level=info msg="Routing match set len: 1/64"
11月 11 12:29:41 v2rayA daed[3948]: time="2023-11-11T12:29:41+08:00" level=warning msg="[Reload] Received reload signal; prepare to reload"
11月 11 12:29:41 v2rayA daed[3948]: time="Nov 11 12:29:41" level=warning msg="[Reload] Load new control plane"
11月 11 12:29:41 v2rayA daed[3948]: time="Nov 11 12:29:41" level=info msg="Waiting for network..."
11月 11 12:29:41 v2rayA daed[3948]: time="Nov 11 12:29:41" level=info msg=Ready
11月 11 12:29:46 v2rayA daed[3948]: time="2023-11-11T12:29:46+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:58713: i/o timeout"
11月 11 12:29:46 v2rayA daed[3948]: time="2023-11-11T12:29:46+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:38303: i/o timeout"
11月 11 12:29:47 v2rayA daed[3948]: time="2023-11-11T12:29:47+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:59774: i/o timeout"
11月 11 12:29:47 v2rayA daed[3948]: time="2023-11-11T12:29:47+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:54767: i/o timeout"
11月 11 12:29:51 v2rayA daed[3948]: time="2023-11-11T12:29:51+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:40497: i/o timeout"
11月 11 12:29:51 v2rayA daed[3948]: time="2023-11-11T12:29:51+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:32951: i/o timeout"
11月 11 12:29:51 v2rayA daed[3948]: time="2023-11-11T12:29:51+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:45065: i/o timeout"
11月 11 12:29:51 v2rayA daed[3948]: time="2023-11-11T12:29:51+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:51700: i/o timeout"
11月 11 12:29:51 v2rayA daed[3948]: time="2023-11-11T12:29:51+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:54673: i/o timeout"
11月 11 12:29:51 v2rayA daed[3948]: time="2023-11-11T12:29:51+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:34558: i/o timeout"
11月 11 12:29:52 v2rayA daed[3948]: time="2023-11-11T12:29:52+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:56345: i/o timeout"
11月 11 12:29:52 v2rayA daed[3948]: time="2023-11-11T12:29:52+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:58441: i/o timeout"
11月 11 12:29:52 v2rayA daed[3948]: time="2023-11-11T12:29:52+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:49228: i/o timeout"
11月 11 12:29:52 v2rayA daed[3948]: time="2023-11-11T12:29:52+08:00" level=warning msg="handlePkt: failed to read from: 192.168.100.144:53 (dialer: direct): read udp [::]:46966: i/o timeout"
```

### Expected Behavior

能正常启动，恢复运行

### Environment

- **Dae version (use `dae --version`)**: 看日志是v0.2.0，daed：v0.4.0rc1
- **OS (e.g `cat /etc/os-release`)**: Debian GNU/Linux 12 (bookworm)
- **Kernel (e.g. `uname -a`)**: Linux v2rayA 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
- **Others**:

### Anything else?
请教一下现在该如何恢复呀？重启系统也没起作用 囧

**Comment by kyleli666** [comment]
disbale daed，然后重启系统，再start daed，可以启动了。在daed界面停止代理再重开，代理也恢复正常。
TG大佬提示可以用这个版本 https://github.com/daeuniverse/daed/actions/runs/6597716868
我去试试。

**Comment by kyleli666** [comment]
改用以上版本后目前没问题了。
