### ISSUE TITLE
[Bug Report] Program crashes after running for a while

### ISSUE THREAD

**Issue by TnZzZHlp** [daeuniverse/dae#685]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

```
time="Nov 04 08:18:01" level=warning msg="handlePkt: failed to GetOrCreate: failed to select dialer from group proxy (udp4, dns?:false,from: 192.168.3.6:36570): no alive dialer"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x143de0]

goroutine 276432 [running]:
fmt.(*wrapErrors).Unwrap(0x0?)
        fmt/errors.go:77
errors.is({0xf85980?, 0x0?}, {0xf84dc0, 0x4000044290}, 0x1)
        errors/wrap.go:68 +0x220
errors.is({0xf85980?, 0x4005a08780?}, {0xf84dc0, 0x4000044290}, 0x1)
        errors/wrap.go:69 +0x260
errors.Is({0xf85980, 0x4005a08780}, {0xf84dc0, 0x4000044290})
        errors/wrap.go:50 +0x98
github.com/daeuniverse/dae/component/sniffing.IsSniffingError(...)
        github.com/daeuniverse/dae/component/sniffing/sniffing.go:23
github.com/daeuniverse/dae/control.(*ControlPlane).handleConn(0x40001ee5a0, {0xf99398, 0x4005e4c9f0})
        github.com/daeuniverse/dae/control/tcp.go:34 +0x168
github.com/daeuniverse/dae/control.(*ControlPlane).Serve.func4.1({0xf99398, 0x4005e4c9f0})
        github.com/daeuniverse/dae/control/control_plane.go:789 +0xc0
created by github.com/daeuniverse/dae/control.(*ControlPlane).Serve.func4 in goroutine 10
        github.com/daeuniverse/dae/control/control_plane.go:786 +0x44
```

### Steps to Reproduce

After running for a while, it crashes.

### Environment

- **Dae version (use `dae --version`)**: 0.9.0rc1
- **OS (e.g `cat /etc/os-release`)**: ImmortalWrt SNAPSHOT r32098-f6d00e7c0d
- **Kernel (e.g. `uname -a`)**: Linux ImmortalWrt 6.6.56 #0 SMP Sat Oct 19 07:13:05 2024 aarch64 GNU/Linux
- **Others**: [Config](https://pastebin.com/yuZEkKwG)
- **Arch**: ARMv8 Processor rev 4

**Comment by mzz2017** [comment]
不应该运行到这个地方的，复现不能，等待其他人复现吧

**Comment by mzz2017** [comment]
@TnZzZHlp 你可以使用 https://github.com/daeuniverse/dae/releases/download/v0.8.0/dae-linux-arm64.zip 里的二进制替换掉你的 dae 再试一下吗

**Comment by mzz2017** [comment]
不是 cgo 的问题，1.23 应该是比较高了，我本来怀疑的是 gosdk 版本

**Comment by mzz2017** [comment]
@TnZzZHlp 好的

**Comment by MarksonHon** [comment]
@TnZzZHlp 开新issue报告
